config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  # resources :answers
  
  resources :questions do
    resources :answers, only: [:create, :index]
  end
  
  resources :users
  
  # namespace :api, format: 'json' do
  #   namespace :v1 do
  #     resources :questions
  #     resources :answers
  #   end
  # end
  
  root "questions#index"
end

app/models/question.rb
class Question < ApplicationRecord
  validates :content, length: { maximum: 500 }
  belongs_to :user
  has_many :answers
end

app/controllers/api/v1/question_controller.rb
require "#{Rails.root}/app/controllers/application_controller.rb"

class Api::V1::QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.all
    render json: @questions
  end

  def show
    @question = Question.find_by(id: params[:id])
    @answers = @question.answers.all
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find_by(id: params[:id])
  end

  def create
    @question = current_user.questions.build(question_params)

    respond_to do |format|
      if @question.save
        format.json { render :show, status: :created, location: @question }
      else
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:content, :url, :title)
    end
    
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # before_action :set_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.all
    @answer = Answer.new
  end

  def show
    @question = Question.find_by(id: params[:id])
    @answers = @question.answers.all
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find_by(id: params[:id])
  end

  def create
    @question = current_user.questions.build(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to root_url, notice: '質問を作成しました' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # def set_question
    #   @question = Question.find(params[:id])
    # end

    def question_params
      params.require(:question).permit(:content, :url, :title)
    end
    
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<h5>質問作成ページ</h5>
<div class="row">
  <div class="col-xs-12 col-sm-offset-4 col-sm-4">
    <%= render 'shared/error_messages', something: @question %>
  </div>
  <div class="col-xs-12">
    <%= form_for(@question, html: { multipart: true }) do |f| %>
      <div class="col-xs-12 col-md-6">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
        
        <%= f.label :content %>
        <%= f.text_field :content, class: 'form-control' %>
  
        <%= f.label :url %>
        <%= f.text_field :url, class: 'form-control' %>
        
        <%= f.submit "質問する", class: "btn btn-primary col-xs-12 col-md-12", data: { disable_with: "送信中..." } %>
      </div>
      
    <% end %>
  </div>
</div>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<div class="container" style="heght: 100vh; width:80vw;">
  <section class="questions" style="margin-top: 10%;">
    <h1 style="font-weight: bold">質問一覧</h1>
    <div class="questions_list" style="margin-top: 5%;">
      <% @questions.each do |question| %>
        <% unless question.answers.count.blank? %>
          <div class="questions_list_question" style="border-bottom: solid 2px #ddd; text-align: center; margin-bottom: 5vh; clear: both;">
            <h2><%= question.content %></h2>
            <a href="<%= question.url %>" class="question_url"><%= question.url %></a>
  
          <%= form_for Answer.new, url: question_answers_path(question.id) do |f| %>
  
            <%= f.text_field :content, class: "form-control" %>
            <br>
            <%= f.submit '回答する', class: 'btn btn-primary submit' %>
          <% end %>
  
          <%# question.answers.each do |answer| %>
           <%#= answer.content %>
          <%# end %>
        </div>
      <% end %>  
        
      <% end %>  

    </div>
  </section>
</div>

app/views/questions/new.html.erb
<h1>質問作成</h1>

<%= render 'form', question: @question %>

<%= link_to '質問一覧へ', questions_path %>

app/views/questions/show.html.erb
<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>
<% @answers.each do |answer| %>
  <%= answer.user.name %>
  <%= answer.content %>
<% end %>