config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  # resources :answers
  
  resources :questions do
    resources :answers, only: [:create, :index]
  end
  
  resources :users
  
  # namespace :api, format: 'json' do
  #   namespace :v1 do
  #     resources :questions
  #     resources :answers
  #   end
  # end
  
  root "questions#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions
  has_many :answers
  
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
                    
  has_secure_password
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
    @questions = @user.questions.all
    @answers = @user.answers.all
  end

  def new
    @user = User.new
  end

  def edit
    @user = current_user
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # def set_user
    #   @user = User.find(params[:id])
    # end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 200)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<% if false %> 
  <%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
  
        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
<% end %>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(user, url: signup_path) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "会員登録", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>会員登録ページ</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="container" style="heght: 100vh; width:80vw;">
  <section class="user_info" style="margin-top: 10%;">
    <div class="user_info_contents" style="margin-top: 5%; display: flex;">
        <%= gravatar_for @user %>
      <div style="padding-left: 100px; margin-top:0; padding-bottom: 10px;">
        <h1 style="font-size: 60px;"><%= @user.name %></h1>
        <h2 class="user_class" style="font-size: 30px;">
          <% if @user.answers.count >= 1 %>知識人<% end %>
          <% if @user.answers.count >= 5 %>救世主<% end %>
        </h2>
        <p style="font-size: 20; padding-bottom: 10px;">
          回答数：<%= @user.answers.count %>
        </p>
      </div>
    </div>
  </section>

  <section class="history" style="height: 100%; margin-top: 10vh; display: flex; justify-content: space-around;">
    <div class="user_answer" style="margin-right: 10px; margin-left: 10px;">
      <h2>今までに回答した質問</h2>
      <div class="user_answers_list" style="display: flex flex-direction: column;">
        <% @answers.each do |answer| %>
          <div class="answers_answer" style="text-align: center; font-size">
              <span class="fa fa-heart col-xs-3"style="color: rgb(223, 86, 86);"></span>
                <%= answer.content %>
            </div>
        <% end %>
      </div>
    </div>


    <div class="user_question" style="margin-right: 10px; margin-left: 10px;">
      <h2>今までにした質問</h2>
        <div class="user_answers_list" style="display: flex flex-direction: column;">
          <% @questions.each do |question| %>
            <div class="questions_question" style="margin-top: 15px;">
              <span class="fa fa-heart col-xs-3"style="color: rgb(223, 86, 86);"></span>
                <%= question.title %>
            </div>
          <% end %>
        </div>
    </div>


  </section>
</div>