config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  # resources :answers
  
  resources :questions do
    resources :answers, only: [:create, :index]
  end
  
  resources :users
  
  # namespace :api, format: 'json' do
  #   namespace :v1 do
  #     resources :questions
  #     resources :answers
  #   end
  # end
  
  root "questions#index"
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" style="back-ground-color: #394a6d;">
  <div class="container">
    <nav  style="height: 10vh;">
      <div class="wrapper_header" style="height: 100%;">
        <%= link_to image_tag("logo.png"), root_path, id: "logo"%>
      </div>
         
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "質問作成", new_question_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "マイページ", user_path(current_user.id) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all','data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application','data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">

  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="wrapper">
      <%= yield %>
    </div>  
  </body>
</html>